---
apiVersion: v1
kind: Secret
metadata:
  name: leap-update-script
  namespace: system-upgrade
type: Opaque
stringData:
  update.sh: |
    #!/bin/bash
    set -e
    zypper up -y
    # It is important to check if reboot if needed otherwise you will get in a reboot loop.
    zypper needs-rebooting; REBOOT=$?
    zypper ps | grep "You may wish to restart these processes"; REBOOT_PS=$? 
    if [ "$REBOOT" == "1" ] || [ "$REBOOT_PS" == "1" ]; then
      reboot
    fi
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: leap-update-2
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/control-plane, operator: Exists}
  tolerations:
    - {key: node-role.kubernetes.io/control-plane, effect: NoSchedule, operator: Exists}
    - {key: node-role.kubernetes.io/etcd, effect: NoExecute, operator: Exists}
  serviceAccountName: system-upgrade
  secrets:
    - name: leap-update-script
      path: /host/run/system-upgrade/secrets/leap-update-script
  drain:
    force: true
  version: leap
  upgrade:
    image: registry.opensuse.org/opensuse/leap:latest
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/leap-update-script/update.sh"]
